dist: bionic
language: minimal

services:
  - docker

before_install:
  - docker pull azaostro/vignat-deps

install:
  - docker run -dt --name=vignat-deps azaostro/vignat-deps
  - docker cp . vignat-deps:/home/vigor/
  - docker exec vignat-deps sudo chown -R vigor:vigor /home/vigor/nf

script:
  - docker exec vignat-deps /bin/bash test-vigor.sh
