dist: bionic
language: minimal

services:
  - docker

before_install:
  - docker pull dslabepfl/vigor

install:
  - docker run -dt --name=vigor dslabepfl/vigor
  - docker cp . vigor:/home/vigor/
  - docker exec vigor sudo chown -R vigor:vigor /home/vigor/

script:
  - docker exec vigor /bin/bash .travis-test.sh
